### ISSUE TITLE
Server SSL Test

### ISSUE THREAD

**Issue by jedwardsit** [jedwardsit/store#4]
Set up a self signed certificate for the test environment.

**Comment by Jedwards-Eric** [comment]
Very useful guide:  https://www.digitalocean.com/community/tutorials/how-to-create-a-ssl-certificate-on-apache-for-ubuntu-14-04

**Comment by Jedwards-Eric** [comment]
1.  Created a self signed certificate in /etc/apache2/ssl/
2.  Edited this to use the cert server wide:  /etc/apache2/sites-available/default-ssl.conf
3.  Updated Magento to use SSL always.
