### ISSUE TITLE
Email setup

### ISSUE THREAD

**Issue by jedwardsit** [jedwardsit/store#6]
Get email setup on test and live servers.

**Comment by jedwardsit** [comment]
https://help.ubuntu.com/community/MailServer
https://www.digitalocean.com/community/tutorials/how-to-install-and-setup-postfix-on-ubuntu-14-04

**Comment by Jedwards-Eric** [comment]
I think it uses zend mail.  Can I alter smtp in php.ini to point to an exchange account and server?

**Comment by Jedwards-Eric** [comment]
The default sendmail configuration appears functional.  Stick with this for now unless we have issues.
